---
title: Kvantitatiivse andmeanalüüsi alused humanitaarteadlastele ja rakendustarkvara
  R (FLFL.00.009)
knit: (function(input_file, encoding) {
    out_dir <- 'docs';
    rmarkdown::render(input_file,
      encoding=encoding,
      output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
date: kevad 2022 
author: Maarja-Liisa Pilvik, Pärtel Lippus (Tartu Ülikool)
output: 
  html_document:
    theme: flatly
    highlight: tango
    self_contained: true
---


1. [Sissejuhatus](kvanthum.github.io/1-sissejuhatus.html)  
2. [Andmetüübid ja objektitüübid](kvanthum.github.io/2-andmetyybid_objektityybid.html)  
3. [Arvulised andmed ja nende visualiseerimine](kvanthum.github.io/3-arvulised.html)  
4. [Kategoriaalsed andmed ja nende visualiseerimine](kvanthum.github.io/4-kategoriaalsed.html)  
5. [Pakett `ggplot2` andmete visualiseerimiseks](kvanthum.github.io/5-ggplot2.html) 
6. [Pakett `tidyverse` andmete töötlemiseks](kvanthum.github.io/6-tidyverse.html) 
7. [Valim ja populatsioon. Hüpoteesid ja tõenäosus](kvanthum.github.io/7-valim_hypoteesid.html)  
8. [Parameetrilised ja mitteparameetrilised testid](kvanthum.github.io/8-parameetrilised_mitteparameetrilised.html) 
9. [Arvuliste tunnuste vahelised seosed](kvanthum.github.io/9-arvuliste_seosed.html) 
10. [Mittearvuliste tunnuste vahelised seosed](kvanthum.github.io/10-mittearvuliste_seosed.html)  
11. [Lineaarse regressiooni mudelid (1)](kvanthum.github.io/11-lineaarsed1.html) 
12. [Lineaarse regressiooni mudelid (2)](kvanthum.github.io/12-lineaarsed2.html) 
13. [Lineaarse regressiooni segamudelid](kvanthum.github.io/13-lineaarsed_sega.html) 
14. [Logistilise regressiooni mudelid (1)](kvanthum.github.io/14-logistilised1.html)  
15. [Logistilise regressiooni mudelid (2)](kvanthum.github.io/15-logistilised2.html) 
16. [Logistilise regressiooni mudelid (3) ja logistilise regressiooni segamudelid](kvanthum.github.io/16-logistilised3_sega.html)  
17. [Tingimuslikud otsustuspuud](kvanthum.github.io/17-otsustuspuud.html) 
18. [Juhumetsad](kvanthum.github.io/18-juhumetsad.html) 